# Generated by Django 2.0.5 on 2018-07-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180716_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Norman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.BooleanField()),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
