# Generated by Django 2.0.4 on 2018-07-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_norman'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('pic_name', models.CharField(max_length=50)),
                ('pic_desc', models.CharField(default='', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
