# Generated by Django 2.0.4 on 2018-07-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180717_0851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Norman',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='uploadpic',
            name='pic_name',
            field=models.CharField(max_length=100),
        ),
    ]
